baseURL = "https://www.47uf.dev/"
languageCode = "en-us"
title = "47uf.dev"
theme = "coder"

[deployment]
[[deployment.targets]]
# An arbitrary name for this target.
name = "sa"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
URL = "azblob://$web"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true